
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uvenu
 */
public class appStart extends javax.swing.JFrame {

    /**
     * Creates new form appStart
     */
    public appStart() {
        super("Air conditioning");
        initComponents();
        initZonesAndOutlets(); //initialising with minimum permitted values
        this.statusTechnician = false;
        enableInstallationEntry(statusTechnician); //disabling data entry for installation initially
        this.setSize(1200, 800);
        this.setResizable(false);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayInstallationsTable = new javax.swing.JTable();
        buttonsPanel = new java.awt.Panel();
        exitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        empPanel = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addEmpBtn = new javax.swing.JButton();
        clearTechnicianButton = new javax.swing.JButton();
        errorTechLabel = new javax.swing.JLabel();
        errorTechnicianLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        installationPanel = new java.awt.Panel();
        addressTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        zoneSpinner = new javax.swing.JSpinner();
        outletSpinner = new javax.swing.JSpinner();
        addInstallationButton = new javax.swing.JButton();
        technicianCbx = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        clearInstallationButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        installationErrorLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Student Id : 1234567");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Student Name : AC ");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(256, 256, 256)
                .addComponent(jLabel11)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayPanel.setName("displayPanel"); // NOI18N

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "Phone"
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        displayInstallationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Technician", "Zones", "Outlets", "Start", "End"
            }
        ));
        jScrollPane2.setViewportView(displayInstallationsTable);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel2.setText("Name");

        jLabel8.setText("Id");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Technician");

        addEmpBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addEmpBtn.setText("Add Technician");
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        clearTechnicianButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearTechnicianButton.setText("Clear");
        clearTechnicianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTechnicianButtonActionPerformed(evt);
            }
        });

        errorTechLabel.setForeground(new java.awt.Color(255, 51, 0));
        errorTechLabel.setText(" ");

        errorTechnicianLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorTechnicianLabel.setText("            ");

        jLabel14.setText("Phone");

        javax.swing.GroupLayout empPanelLayout = new javax.swing.GroupLayout(empPanel);
        empPanel.setLayout(empPanelLayout);
        empPanelLayout.setHorizontalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorTechLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(errorTechnicianLabel)))
                .addGap(83, 83, 83))
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addEmpBtn)
                        .addGap(38, 38, 38)
                        .addComponent(clearTechnicianButton))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        empPanelLayout.setVerticalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(errorTechnicianLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addComponent(errorTechLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmpBtn)
                    .addComponent(clearTechnicianButton))
                .addGap(38, 38, 38))
        );

        jLabel3.setText("Address");

        jLabel4.setText("Num Zones");

        jLabel5.setText("Num Outlets");

        jLabel7.setText("Start Date");

        jLabel6.setText("End Date");

        addInstallationButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addInstallationButton.setText("Add Installation");
        addInstallationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstallationButtonActionPerformed(evt);
            }
        });

        technicianCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianCbxActionPerformed(evt);
            }
        });

        jLabel9.setText("Technician");

        clearInstallationButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearInstallationButton.setText("Clear");
        clearInstallationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearInstallationButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Installation");

        installationErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        installationErrorLabel.setText("  ");

        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("e.g., 2019-06-29");
        jLabel13.setEnabled(false);

        javax.swing.GroupLayout installationPanelLayout = new javax.swing.GroupLayout(installationPanel);
        installationPanel.setLayout(installationPanelLayout);
        installationPanelLayout.setHorizontalGroup(
            installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(installationPanelLayout.createSequentialGroup()
                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(installationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(installationPanelLayout.createSequentialGroup()
                                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(60, 60, 60)
                                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(installationPanelLayout.createSequentialGroup()
                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(installationErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(installationPanelLayout.createSequentialGroup()
                                        .addComponent(zoneSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5)
                                        .addGap(44, 44, 44)
                                        .addComponent(outletSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(installationPanelLayout.createSequentialGroup()
                                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(60, 60, 60)
                                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(clearInstallationButton)
                                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(installationPanelLayout.createSequentialGroup()
                                        .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9)
                                        .addGap(35, 35, 35)
                                        .addComponent(technicianCbx, 0, 225, Short.MAX_VALUE))))
                            .addComponent(addInstallationButton)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, installationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(294, 294, 294))))
                    .addGroup(installationPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );

        installationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        installationPanelLayout.setVerticalGroup(
            installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(installationPanelLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(47, 47, 47)
                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(installationPanelLayout.createSequentialGroup()
                        .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(installationErrorLabel))
                        .addGap(18, 18, 18)
                        .addComponent(outletSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(zoneSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(technicianCbx))
                .addGap(29, 29, 29)
                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(installationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInstallationButton)
                    .addComponent(clearInstallationButton)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(empPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(installationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(installationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(empPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(977, Short.MAX_VALUE)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(830, 830, 830))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void initZonesAndOutlets(){
        //setting min and max values
        this.zoneSpinner.setModel(new SpinnerNumberModel (1,AppValues.MIN_ZONE,AppValues.MAX_ZONE,1));
        this.outletSpinner.setModel(new SpinnerNumberModel (1,AppValues.MIN_OUTLET,AppValues.MAX_OUTLET,1));
    }
    private void enableInstallationEntry(boolean ready){
        //enabling/disabling data entry in installation fields 
        this.technicianCbx.setEnabled(ready);
        this.addressTextField.setEnabled(ready);
        this.addInstallationButton.setEnabled(ready);
        this.endDateTextField.setEnabled(ready);
        this.outletSpinner.setEnabled(ready);
        this.startDateTextField.setEnabled(ready);
        this.zoneSpinner.setEnabled(ready);
        this.technicianCbx.setEnabled(ready);
        this.clearInstallationButton.setEnabled(ready);
        
    }
    
    private void displayTechnician(){
        
        DefaultTableModel currentModel = (DefaultTableModel) this.displayTable.getModel();
        currentModel.setRowCount(0);
        Object [] row = new Object[3];
        for (int i = 0; i<this.lstTechnicians.size(); i++){
            //creating each row of Technician
            row[0] = this.lstTechnicians.get(i).getEmpId();
            row[1] = this.lstTechnicians.get(i).getName();
            row[2] = this.lstTechnicians.get(i).getPhoneNum();
            //adding the row to the table
            currentModel.addRow(row);
        }
        this.displayTable.setVisible(true);
        
    }
    private boolean isTextFieldEmpty(JTextField aTextField){
        // checking whehether the param-text field is empty
        if (aTextField.getText().isEmpty())
            return true;
        return false;
    }
    private boolean checkTechnicianFields(){
        
       try{
           //if the id is not blank then check the id is not in the exising list 
           if(isTextFieldEmpty(this.idTxt)){
                this.errorTechLabel.setText("Enter Id");
                return false;
            }
            else if (existingEmp(this.idTxt.getText())){
                return false;
            }
            //check the name is not blank
            if(isTextFieldEmpty(this.nameTxt)) {
                this.errorTechLabel.setText("Enter name");
                return false;
            }
            
       }
       catch(Exception e)
        {
            this.errorTechLabel.setText("Enter correct values for Technician");
            return false;
        }
       return true; 
    }   
    private boolean existingEmp(String pId){
        int empId = Integer.parseInt(pId);
        for (Technician t: lstTechnicians){ 
            if(t.getEmpId() == empId)  {
                this.errorTechLabel.setText("Technician Id has to be unique");
                return true;
            }
        }
        
        return false;
    }
    
    private void makeTechnician(Technician aTechnician){
        if(checkTechnicianFields()){
            try{
                aTechnician.setEmpId(Integer.parseInt(this.idTxt.getText()));
            }catch (Exception e)
            {
                this.errorTechLabel.setText("Enter number for Id");
            }
            aTechnician.setName(this.nameTxt.getText());
            aTechnician.setPhoneNum(this.phoneTxt.getText());
            addTechnicianToList(aTechnician);
            displayTechnician();  
        }           
    }
    private void addTechnicianToList(Technician aTechnician){
        this.lstTechnicians.add(aTechnician);
        updateTechnicianComboBox();
    }
    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        this.errorTechLabel.setText("");
        Technician pTechnician = new Technician();
        makeTechnician(pTechnician);
       
    }//GEN-LAST:event_addEmpBtnActionPerformed

    private void clearTechnicianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTechnicianButtonActionPerformed
         this.errorTechLabel.setText("");
         this.idTxt.setText("");
         this.nameTxt.setText("");
    }//GEN-LAST:event_clearTechnicianButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // 
        int ok = JOptionPane.showConfirmDialog(null, "Do you want to Exit the application");
        if (ok == JOptionPane.OK_OPTION)
            System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearInstallationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearInstallationButtonActionPerformed
        // 
        this.addressTextField.setText("");
        this.zoneSpinner.setValue(1);
        this.outletSpinner.setValue(1);
        this.updateTechnicianComboBox();
        this.startDateTextField.setText("");
        this.endDateTextField.setText("");
        this.installationErrorLabel.setText("");
        
    }//GEN-LAST:event_clearInstallationButtonActionPerformed
    
    private boolean checkInstallationFields(){
        //checking installation address is not blank and is not repeationg and technician is selected
        try{
            if(this.isTextFieldEmpty(addressTextField)){
                this.installationErrorLabel.setText("Enter address");
                return false;
            }
            if (existingInstallation(this.addressTextField.getText())){               
                return false;
            }
            if (this.technicianCbx.getSelectedIndex()<0){
                this.installationErrorLabel.setText("Select Technician");
                return false;
            }
        }catch(Exception e){
            this.installationErrorLabel.setText("Installation fields error");
        }
        return true;
    }
     private boolean existingInstallation(String aAddress){
        //installation address is checked for duplicate entry        
        for (Installation i: lstInstallations){ 
            if(i.getAddress().equalsIgnoreCase(aAddress))  { // new installation address is in the list
                this.installationErrorLabel.setText("Installation address is repeating");
                return true;
            }
        }
        return false; // new installation address is not in the list
    }
     private void addInstallationToList (Installation aInstallation){
         //new installation is added successfully
         this.installationErrorLabel.setText("Added new Installation");
         this.lstInstallations.add(aInstallation);
         
     }      
     private void displayInstallation (){
         
        DefaultTableModel currentModel = (DefaultTableModel) this.displayInstallationsTable.getModel();
        currentModel.setRowCount(0);
        Object [] row = new Object[6];
        for (int i = 0; i<this.lstInstallations.size(); i++){
            //creating and adding each row of installation to the table model
            row [0] = this.lstInstallations.get(i).getAddress().toString();
            row[1] = this.lstInstallations.get(i).getEmployee().getName();
            row[2] = this.lstInstallations.get(i).getNumZones();            
            row[3] = this.lstInstallations.get(i).getNumOutlets();
            row[4] = this.lstInstallations.get(i).getStartDate().toString();
            row[5] = this.lstInstallations.get(i).getEndDate().toString();
            currentModel.addRow(row);
        }
        this.displayInstallationsTable.setVisible(true);
         
     }      
    private void makeInstallation(Installation aInstallation){
        Technician selecetedTechnician = new Technician();
        //Verify the fields are not empty and then create a new installation and add it to the list
        if(checkInstallationFields()){
            try{
                String s1 = this.startDateTextField.getText();
                LocalDate pStartDate = LocalDate.parse(s1);
                aInstallation.setStartDate(pStartDate);
                String s2 = this.endDateTextField.getText();
                LocalDate pEndDate = LocalDate.parse(s2);
                pEndDate = LocalDate.parse(s2);
                if(pEndDate.compareTo(pStartDate)>=0) // checking end date is on or after the start date
                    aInstallation.setEndDate(pEndDate);
                else 
                    throw new Exception();
                if(this.technicianCbx.getSelectedIndex()!= -1)
                    selecetedTechnician = this.lstTechnicians.get(this.technicianCbx.getSelectedIndex());
                //setting the new installation's fields
                aInstallation.setAddress(this.addressTextField.getText());
                aInstallation.setEmployee(selecetedTechnician);
                aInstallation.setNumZones(Integer.parseInt(this.zoneSpinner.getValue().toString()));
                aInstallation.setNumOutlets(Integer.parseInt(this.outletSpinner.getValue().toString()));
                addInstallationToList(aInstallation);
                displayInstallation();  
            }catch (Exception e)
            {
                this.installationErrorLabel.setText("Error in date values");
            }
            
        }           
    }
    private void addInstallationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstallationButtonActionPerformed
        //Clear the installation error label contents
        this.installationErrorLabel.setText("");
        Installation pInstallation = new Installation();
        makeInstallation(pInstallation);
    }//GEN-LAST:event_addInstallationButtonActionPerformed

    private void technicianCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_technicianCbxActionPerformed
    private void updateTechnicianComboBox(){
        // filling combo box with the existing Technicians 
        DefaultComboBoxModel c = (DefaultComboBoxModel)this.technicianCbx.getModel();
        c.removeAllElements();
        String idName ="";
        for(Technician t:this.lstTechnicians){
            //combine id and name of the technician to display in the combo box
            idName = t.getEmpId()+ ": " + t.getName();
            this.technicianCbx.addItem(idName);                                
        }
        this.technicianCbx.repaint();
             
        this.technicianCbx.setSelectedIndex(this.lstTechnicians.size()-1);
        
        if (this.technicianCbx.getItemCount()>0){
            this.statusTechnician = true;
            enableInstallationEntry(statusTechnician);
        }
        
        this.addressTextField.setFocusable(true);
     } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton addInstallationButton;
    private javax.swing.JTextField addressTextField;
    private java.awt.Panel buttonsPanel;
    private javax.swing.JButton clearInstallationButton;
    private javax.swing.JButton clearTechnicianButton;
    private javax.swing.JTable displayInstallationsTable;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTable displayTable;
    private java.awt.Panel empPanel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel errorTechLabel;
    private javax.swing.JLabel errorTechnicianLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel installationErrorLabel;
    private java.awt.Panel installationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JSpinner outletSpinner;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JComboBox<String> technicianCbx;
    private java.awt.Panel titlePanel;
    private javax.swing.JSpinner zoneSpinner;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Technician> lstTechnicians = new ArrayList<>();
    private ArrayList<Installation> lstInstallations = new ArrayList<>();
    private boolean statusTechnician;
}
